### ISSUE TITLE
Simplify free ports selection in JUnit5 unit tests

### ISSUE THREAD

**Issue by sip3leo** [sip3io/sip3-salto-ce#5]
As mentioned in [pull request comment](https://github.com/sip3io/sip3-salto-ce/pull/3#discussion_r359193589) we need to add JUnit5 Extension.  New extension should simplify free ports(one and more) selection in Unit tests.

**Comment by agafox** [comment]
https://github.com/sip3io/sip3-commons/pull/10

**Comment by agafox** [comment]
As long as most of our complex tests are `VertxTest` instances we can just add `findRandomPort` as a method of the class.

**Comment by agafox** [comment]
TODO is fixed in this PR: https://github.com/sip3io/sip3-salto-ce/pull/6
